### ISSUE TITLE
Bubble tea navigation help does not specify "enter" to make a menu selection

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/ficsit-cli#20]
Maybe help text for this is overkill, but it's the only interaction currently left out of the help text, as far as I know.

#11 fixed this for q to go back, but unlike the Quit binding, it's not really clear to me what the Accept binding is called for the purpose of adding this. Tried `NextPage` and `AcceptWhileFiltering` on a whim but they are other totally separate bindings.

**Comment by samox73** [comment]
AFAIK, per default the `bubbles` `list` component should have the `Enter` key in the help bar. If we cannot figure out why it is not displayed we could force-add it with:
```
list.AdditionalShortHelpKeys = func() []key.Binding {
	return []key.Binding{
		key.NewBinding(key.WithKeys("Enter"), key.WithHelp("Enter", "select")),
	}
}

```
