### ISSUE TITLE
Invalid semver error on valid semver

### ISSUE THREAD

**Issue by surdaft** [satisfactorymodding/ficsit-cli#38]
### What happened?

![image](https://github.com/satisfactorymodding/ficsit-cli/assets/8268249/001d42c0-a7e1-4615-92d5-6063ef69b71b)

installing 0.9.8 works as expected, 0.10.0 does not

### Version

72a6094ad39ea34c0609d1f0b1aac6e865e59ff6

### What OS are you seeing the problem on?

Linux

### What architecture are you seeing the problem on?

amd64

### Relevant log output

```shell
na
```

### Any extra info:

na

**Comment by Vilsol** [comment]
Fixed
