### ISSUE TITLE
Softlock when restoring mods

### ISSUE THREAD

**Issue by Kevok93** [satisfactorymodding/ficsit-cli#5]
### What happened?

When attempting to restore/update mods, one mod was unable to be restored due to a missing dependency (Probably due to UP6). Rather than crash or provide some other form of error/exit prompt, the app only hangs indefinitely; no button press that I could deduce will make the application change state, and no cpu/network activity is observed. The only way out is to kill the process manually. 

![image](https://user-images.githubusercontent.com/8062278/178636574-e58b720b-22cd-45e9-91ea-e942a22ed360.png)

### Version

0.1.2 - 5ac338f2

### What OS are you seeing the problem on?

Linux

### What architecture are you seeing the problem on?

amd64

**Comment by Vilsol** [comment]
Should be fixed, please test
